### PR TITLE
verify Circles is enabled

### LINKED ISSUE #3: App breaks hard and kills occ when circles is disabled
### Steps
1. Install NC
2. Enable this app
3. Disable circles with `occ app:disable circles`
4. See that everything is broken
5. Try to disable related_resources: 💥
```
sudo -u www-data php occ app:disable related_resources
An unhandled exception has been thrown:
OCP\AppFramework\QueryException: Could not resolve OCA\Circles\CirclesManager! Class "OCA\Circles\CirclesManager" does not exist in /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:122
Stack trace:
#0 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Circles\\Cir...')
#1 /var/www/cloud.nextcloud.com/nextcloud/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Circles\\Cir...', true)
#2 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query('OCA\\Circles\\Cir...')
#3 /var/www/cloud.nextcloud.com/nextcloud/apps-extra/related_resources/lib/Service/RelatedService.php(95): OC\AppFramework\Utility\SimpleContainer->get('OCA\\Circles\\Cir...')
#4 [internal function]: OCA\RelatedResources\Service\RelatedService->__construct(Object(OC\App\AppManager), Object(OC\Memcache\Factory), Object(OCA\RelatedResources\Service\ConfigService))
#5 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): ReflectionClass->newInstanceArgs(Array)
#6 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#7 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\RelatedReso...')
#8 /var/www/cloud.nextcloud.com/nextcloud/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query('OCA\\RelatedReso...', true)
#9 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(89): OC\ServerContainer->query('OCA\\RelatedReso...', true)
#10 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#11 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map(Object(Closure), Array)
#12 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#13 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\RelatedReso...')
#14 /var/www/cloud.nextcloud.com/nextcloud/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query('OCA\\RelatedReso...', true)
#15 /var/www/cloud.nextcloud.com/nextcloud/lib/private/Console/Application.php(219): OC\ServerContainer->query('OCA\\RelatedReso...')
#16 /var/www/cloud.nextcloud.com/nextcloud/lib/private/Console/Application.php(130): OC\Console\Application->loadCommandsFromInfoXml(Array)
#17 /var/www/cloud.nextcloud.com/nextcloud/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/cloud.nextcloud.com/nextcloud/occ(11): require_once('/var/www/cloud....')
#19 {main}
```

6. Try to reenable Circles to fix the issue: 💥 
```
sudo -u www-data php occ app:enable circles
An unhandled exception has been thrown:
OCP\AppFramework\QueryException: Could not resolve OCA\Circles\CirclesManager! Class "OCA\Circles\CirclesManager" does not exist in /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:122
Stack trace:
#0 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Circles\\Cir...')
#1 /var/www/cloud.nextcloud.com/nextcloud/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Circles\\Cir...', true)
#2 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query('OCA\\Circles\\Cir...')
#3 /var/www/cloud.nextcloud.com/nextcloud/apps-extra/related_resources/lib/Service/RelatedService.php(95): OC\AppFramework\Utility\SimpleContainer->get('OCA\\Circles\\Cir...')
#4 [internal function]: OCA\RelatedResources\Service\RelatedService->__construct(Object(OC\App\AppManager), Object(OC\Memcache\Factory), Object(OCA\RelatedResources\Service\ConfigService))
#5 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): ReflectionClass->newInstanceArgs(Array)
#6 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#7 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\RelatedReso...')
#8 /var/www/cloud.nextcloud.com/nextcloud/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query('OCA\\RelatedReso...', true)
#9 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(89): OC\ServerContainer->query('OCA\\RelatedReso...', true)
#10 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#11 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map(Object(Closure), Array)
#12 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#13 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\RelatedReso...')
#14 /var/www/cloud.nextcloud.com/nextcloud/lib/private/ServerContainer.php(161): OC\AppFramework\Utility\SimpleContainer->query('OCA\\RelatedReso...', true)
#15 /var/www/cloud.nextcloud.com/nextcloud/lib/private/Console/Application.php(219): OC\ServerContainer->query('OCA\\RelatedReso...')
#16 /var/www/cloud.nextcloud.com/nextcloud/lib/private/Console/Application.php(130): OC\Console\Application->loadCommandsFromInfoXml(Array)
#17 /var/www/cloud.nextcloud.com/nextcloud/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/cloud.nextcloud.com/nextcloud/occ(11): require_once('/var/www/cloud....')
#19 {main}
```

The only way to "fix" this is to just move the related_resources out of the apps-directory.

Instead of getting injected with DI the app should use the circles stuff inside it's code and handle a missing circles gracefully.

### PR DESCRIPTION
**Pull request by ArtificialOwl**
fix #3

### CODE REVIEW

File: lib/Controller/ApiController.php [hunk 1]
```diff
@@ -83,6 +90,12 @@ public function __construct(
 	 * @throws OCSException
 	 */
 	public function getRelatedResources(string $providerId, string $itemId): DataResponse {
+		if (is_null($this->circlesManager)) {
+			$this->logger->log(2, 'RelatedResources require Circles');
```
Comment (come-nc) [inline lib/Controller/ApiController.php:94]:
```suggestion
			$this->logger->info('RelatedResources require Circles');
```
No magic number please. (Not sure if info is the right level)
